version: "3.8"
services:
  app_bonos:
    image: app_bonos
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./instance:/app/instance
    environment:
      - PYTHONUNBUFFERED=1